### ISSUE TITLE
let's encrypt

### ISSUE THREAD

**Issue by sahara101** [briandipalma/proxmox-services#2]
Hi and sorry I am still new at ansible. I am trying to install traefik but receiving this:

An exception occurred during task execution. To see the full traceback, use -vvv. The error was: ansible.errors.AnsibleUndefinedVariable: 'acme_email' is undefined. 'acme_email' is undefined
fatal: [traefik.local]: FAILED! => {"changed": false, "msg": "AnsibleUndefinedVariable: 'acme_email' is undefined. 'acme_email' is undefined"}

where exactly do I need to define it?

Thanks!

**Comment by briandipalma** [comment]
It's a variable defined in a variable file: https://github.com/briandipalma/proxmox-services/blob/main/ansible/roles/traefik/tasks/main.yml#L3

```yaml
---
acme_email: email@host.com
```
